{{- if .Values.openai.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.openai.secretName }}
  labels:
    {{- include "kagent.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.openai.secretKey }}: {{ .Values.openai.apiKey | b64enc }}
{{- end }}